# Generated by Django 4.2.7 on 2025-06-15 14:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.PositiveIntegerField(help_text='Stock al momento de generar la alerta')),
                ('stock_minimo', models.PositiveIntegerField(help_text='Stock mínimo configurado al momento de la alerta')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NOTIFICADA', 'Notificada'), ('RESUELTA', 'Resuelta'), ('IGNORADA', 'Ignorada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada de Stock'), ('SALIDA_USO', 'Salida por Uso en OT'), ('SALIDA_SOLICITUD', 'Salida por Solicitud'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('BAJA_POR_DANHO', 'Baja por Daño/Defecto'), ('COMPRA_EXTERNA_USO_DIRECTO', 'Compra Externa para Uso Directo'), ('DEVOLUCION', 'Devolución a Stock')], max_length=30)),
                ('cantidad', models.IntegerField(help_text='Cantidad de repuestos en el movimiento', validators=[django.core.validators.MinValueValidator(1)])),
                ('stock_anterior', models.PositiveIntegerField(help_text='Stock antes del movimiento')),
                ('stock_posterior', models.PositiveIntegerField(help_text='Stock después del movimiento')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Costo unitario en este movimiento', max_digits=10, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, help_text='Motivo del movimiento, notas adicionales')),
                ('proveedor', models.CharField(blank=True, help_text='Proveedor en caso de entrada', max_length=200)),
                ('numero_factura', models.CharField(blank=True, help_text='Número de factura de compra', max_length=100)),
                ('numero_ot', models.CharField(blank=True, help_text='Número de OT para compras externas directas', max_length=50)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AlterModelOptions(
            name='repuesto',
            options={'ordering': ['nombre'], 'verbose_name': 'Repuesto', 'verbose_name_plural': 'Repuestos'},
        ),
        migrations.RenameField(
            model_name='repuesto',
            old_name='fecha_creacion',
            new_name='creado_en',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='stock_minimo',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras para identificación rápida', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo unitario promedio', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca del repuesto', max_length=100),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo específico', max_length=100),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock_minimo_seguridad',
            field=models.PositiveIntegerField(default=1, help_text='Nivel mínimo antes de generar alerta', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='unidad_medida',
            field=models.CharField(default='unidades', help_text='Unidad de medida (ej: unidades, metros, kilos)', max_length=20),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si el repuesto está disponible para uso'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción detallada del repuesto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo del repuesto', max_length=200),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad actual disponible en bodega'),
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['nombre'], name='inventario__nombre_72032b_idx'),
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['codigo_barras'], name='inventario__codigo__5c028e_idx'),
        ),
        migrations.AddIndex(
            model_name='repuesto',
            index=models.Index(fields=['stock_actual'], name='inventario__stock_a_0e11a7_idx'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, help_text='Supervisor que autorizó ajustes o bajas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.repuesto'),
        ),
        migrations.AddField(
            model_name='alertastock',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.repuesto'),
        ),
        migrations.AddField(
            model_name='alertastock',
            name='resuelta_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['repuesto', '-fecha_movimiento'], name='inventario__repuest_6cd7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo_movimiento'], name='inventario__tipo_mo_89d562_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['registrado_por'], name='inventario__registr_b22e08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alertastock',
            unique_together={('repuesto', 'fecha_creacion')},
        ),
    ]
