# Generated by Django 4.2.7 on 2025-06-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alertastock_movimientoinventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
